x-common-config:
  &common-config
  network_mode: host
  ipc: host
  env_file:
    - .env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:

  rosbot_gazebo:
    image: husarion/rosbot-gazebo:humble-0.15.2-20251001
    <<: [*gpu-config, *common-config]
    volumes:
      - ./dds-config-udp.xml:/udp_profile.xml:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch rosbot_gazebo simulation.launch.py
        robot_model:=${ROBOT_MODEL:-err}
        rviz:=False

  rosbot_navigation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    <<: [*common-config]
    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    volumes:
      - ./dds-config-udp.xml:/udp_profile.xml:ro
      - ../rosbot_navigation:/ros2_ws/src/rosbot_autonomy_ros/rosbot_navigation
      - ../maps:/maps
    command: >
      ros2 launch rosbot_navigation bringup.launch.py
        map:=/maps/map.yaml
        params_file:=/ros2_ws/src/rosbot_autonomy_ros/rosbot_navigation/config/nav2_${CONTROLLER:-mppi}_params.yaml
        robot_model:=${ROBOT_MODEL:?err}
        slam:=${SLAM:-True}
        use_sim_time:=True
