x-common-config:
  &common-config
  network_mode: host
  ipc: host

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

services:

  rosbot_gazebo:
    image: husarion/rosbot-gazebo:jazzy-0.16.1-20250901
    <<: [*gpu-config, *common-config]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      ros2 launch rosbot_gazebo simulation.launch.py robot_model:=${ROBOT_MODEL:-err} rviz:=False

  rosbot_navigation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    <<: [*common-config]
    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
    volumes:
      - ../rosbot_navigation:/ros2_ws/src/rosbot_autonomy_ros/rosbot_navigation
      - ../maps:/maps
    command: >
      ros2 launch rosbot_navigation bringup.launch.py
        controller:=${CONTROLLER:-mppi}
        map:=/maps/map.yaml
        robot_model:=${ROBOT_MODEL:-err}
        slam:=${SLAM:-True}
        use_sim_time:=True
